// Angular
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/http';
import '@angular/forms';
import '@angular/router';
// RxJS
import 'rxjs';
//angular material
import 'reflect-metadata';
import '@angular/material';
import '@angular/material/core/theming/prebuilt/deeppurple-amber.css';
import './css/default.css';
import './img/ProjectTracking-SplashScreen.png';
//chartjs
import 'chart.js';
import 'ng2-charts';
//bootstrap style
import 'bootstrap/dist/css/bootstrap-theme.min.css';
import 'bootstrap/dist/css/bootstrap.min.css';
